# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('genre', models.TextField()),
                ('popularity', models.CharField(default='', max_length=100)),
                ('director', models.CharField(blank=True, default='', max_length=100)),
                ('imdb_score', models.CharField(default='0.0', max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
